language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without development production --quiet
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rake spec"
notifications:
  email:
    - ryan@spreecommerce.com
    - jdyer@spreecommerce.com
    - brian@spreecommerce.com
branches:
  only:
    - master
    - 1-0-stable
    - 1-1-stable
    - 1-2-stable
    - 1-3-stable
